---
title: "Thesis code"
author: "Jackson Bandow"
date: "2/5/2021"
output: html_document
---

Libraries necessary for project

```{r}
library(Lahman)
library(rvest)
library(dplyr)
library(readr)
library(httr)
library(data.table)
library(ggplot2)
library(plotly)
```


Import dataset

```{r, include=FALSE}
data("Master")
data("Batting")
data("Pitching")
data("HallOfFame")
```

Compile seasonal stats to career dataset

```{r, include=FALSE}
sum_vec <- function(vec) {
  data <- na.omit(vec)
  if (length(data) == 0) return(NA)
  else return(sum(data))
}

replace_na <- function(vec, rep) {
  res <- vec
  for (i in 1:length(vec)) {
    if (is.na(res[i])) res[i] <- rep
  }
  return(res)
}

# Batting
emp <- rep(NA, length(unique(Batting$playerID)))

batting_career <- data.frame(playerID = unique(Batting$playerID), firstyearID.B = emp, lastyearID.B = emp, G.B = emp, AB = emp, R = emp, H.B = emp, X2B = emp, X3B = emp, HR.B = emp, RBI = emp, SB = emp, CS = emp, BB.B = emp, SO.B = emp, IBB.B = emp, HBP.B = emp, SH.B = emp, SF.B = emp, GIDP.B = emp)

for (i in batting_career$playerID) {
  seasonal <- Batting[Batting$playerID == i,]
  batting_career[batting_career$playerID == i,-1] <- c(min(seasonal$yearID), max(seasonal$yearID), sum_vec(seasonal$G), sum_vec(seasonal$AB), sum_vec(seasonal$R), sum_vec(seasonal$H), sum_vec(seasonal$X2B), sum_vec(seasonal$X3B), sum_vec(seasonal$HR), sum_vec(seasonal$RBI), sum_vec(seasonal$SB), sum_vec(seasonal$CS), sum_vec(seasonal$BB), sum_vec(seasonal$SO), sum_vec(seasonal$IBB), sum_vec(seasonal$HBP), sum_vec(seasonal$SH), sum_vec(seasonal$SF), sum_vec(seasonal$GIDP))
}

# Pitching
emp <- rep(NA, length(unique(Pitching$playerID)))

pitching_career <- data.frame(playerID = unique(Pitching$playerID), firstyearID.P = emp, lastyearID.P = emp, W = emp, L = emp, G.P = emp, GS = emp, CG = emp, SHO = emp, SV = emp, IPout = emp, H.P = emp, ER = emp, HR.P = emp, BB.P = emp, SO.P = emp, BAOpp = emp, ERA = emp, IBB.P = emp, WP = emp, HBP.P = emp, BK = emp, BFP = emp, GF = emp, R = emp, SH.P = emp, SF.P = emp, GIDP.P = emp)

for (i in pitching_career$playerID) {
  seasonal <- Pitching[Pitching$playerID == i,]
  pitching_career[pitching_career$playerID == i,-1] <- c(min(seasonal$yearID), max(seasonal$yearID), sum_vec(seasonal$W), sum_vec(seasonal$L), sum_vec(seasonal$G), sum_vec(seasonal$GS), sum_vec(seasonal$CG), sum_vec(seasonal$SHO), sum_vec(seasonal$SV), sum_vec(seasonal$IPout), sum_vec(seasonal$H), sum_vec(seasonal$ER), sum_vec(seasonal$HR), sum_vec(seasonal$BB), sum_vec(seasonal$SO), sum(seasonal$BFP * seasonal$BAOpp) / sum_vec(seasonal$BFP), sum(seasonal$IPout * seasonal$ERA) / sum_vec(seasonal$IPout), sum_vec(seasonal$IBB), sum_vec(seasonal$WP), sum_vec(seasonal$HBP), sum_vec(seasonal$BK), sum_vec(seasonal$BFP), sum_vec(seasonal$GF), sum_vec(seasonal$R), sum_vec(seasonal$SH), sum_vec(seasonal$SF), sum_vec(seasonal$GIDP))
}
```


Attaching WAR

```{r, include=FALSE}
# Find duplicate indices of df sorted by given col
find_dup_indices <- function(col) {
  data <- sort(col) 
  res <- NULL
  for (i in 1:length(data)) {
    if (data[i] == data[((i-2) %% length(data)) + 1] | data[i] == data[(i %% length(data)) + 1]) {
      res <- append(res, i)
    }
  }
  return(res)
}


# FanGraphs WAR

fan_pitch <- read.csv("FanGraphs Leaderboard (1)pitching.csv")[,c("playerid", "WAR")]
colnames(fan_pitch) <- c("fangraphsID", "fWAR_pitch")
fan_bat <- read.csv("FanGraphs Leaderboard (1).csv")[,c("playerid", "WAR")]
colnames(fan_bat) <- c("fangraphsID", "fWAR_bat")


fangraphs <- data.frame()
#fangraphs <- fangraphs[1:764,]
working <- TRUE
while(working) {
  print(i)
  stat <- status_code(GET(paste0("http://www.fangraphs.com/statss.aspx?playerid=", i)))
  if (stat != 500) {
    page <- read_html(paste0("http://www.fangraphs.com/statss.aspx?playerid=", i))
    name <- page %>% html_nodes("h1") %>% html_text()
    bday <- page %>% html_nodes(".player-info__bio-birthdate td") %>% html_text()
    if (length(name) == 0) working <- FALSE
    else fangraphs <- rbind(fangraphs, c(i, name, bday)) 
  }
  i <- i + 1
}
colnames(fangraphs) <- c("fangraphsID", "Name", "DOB")

fangraphs$birthMonth <- as.integer(gsub("/.*$?", "", fangraphs$DOB))
fangraphs$birthDay <- as.integer(gsub("/.*$?", "", gsub("^[0-9]*/?", "", fangraphs$DOB)))
fangraphs$birthYear <- as.integer(substr(gsub("^[0-9]*/?", "", gsub("^[0-9]*/?", "", fangraphs$DOB)), 1, 4))
fangraphs$birthDate <- as.Date(paste(fangraphs$birthYear, fangraphs$birthMonth, fangraphs$birthDay, sep = "-"))
fangraphs$Name <- trimws(fangraphs$Name)
fangraphs$fangraphsID <- as.integer(fangraphs$fangraphsID)
fangraphs <- fangraphs %>% dplyr::select(c("fangraphsID", "Name", "birthDate"))
fwrite(fangraphs, "fangraphsID.csv")

fangraphs <- fread("fangraphsID.csv")

Master$Name <- paste(Master$nameFirst, Master$nameLast, sep = " ")
Master2 <- Master
Master2 <- left_join(Master2, fangraphs, by = c("Name", "birthDate"))
Master2 <- Master2[order(Master2$fangraphsID),]
Master2[16945,]$fangraphsID <- NA
Master2 <- Master2[-c(15581, 15582, 15641, 15642, 16258, 16259),]
Master2 <- Master2[order(Master2$playerID),]
Master2 <- Master2[-c(12498, 12755),]

leftover_fangraphs <- fangraphs[!(fangraphs$fangraphsID %in% Master2$fangraphsID),]
leftover_Master2 <- Master2[is.na(Master2$fangraphsID),]

leftover_fangraphs$Name <- gsub("~", "", gsub("'", "", iconv(gsub("Jr.", "", gsub("[^[:alnum:] [:punct:]]", "", leftover_fangraphs$Name)), from = "UTF-8", to = "ASCII//TRANSLIT")))
leftover_Master2$Name <- gsub("'", "", leftover_Master2$Name)
# leftover_fangraphs$nameFirst <- gsub(" .*$", "", leftover_fangraphs$Name)
# leftover_fangraphs$nameLast <- gsub(" .*$", "", gsub("^\\S* ", "", leftover_fangraphs$Name))
leftover_Master2_t <- left_join(leftover_Master2, leftover_fangraphs, by = c("Name", "birthDate"))
leftover_Master2_t$fangraphsID <- leftover_Master2_t$fangraphsID.y

dictionary <- Master2 %>% dplyr::select(playerID, bbrefID, fangraphsID)
dictionary <- dictionary[!is.na(dictionary$fangraphsID),]
dictionary <- rbind(dictionary, leftover_Master2_t[!is.na(leftover_Master2_t$fangraphsID), c("playerID", "bbrefID", "fangraphsID")])
fwrite(dictionary, "dictionary.csv")

leftover_fangraphs <- leftover_fangraphs[!(leftover_fangraphs$fangraphsID %in% leftover_Master2_t$fangraphsID),]
leftover_Master2 <- leftover_Master2_t[is.na(leftover_Master2_t$fangraphsID),]

leftover_fangraphs$Name <- gsub(" ", "", leftover_fangraphs$Name)
leftover_Master2$Name <- gsub(" ", "", leftover_Master2$Name)
leftover_Master2_t <- left_join(leftover_Master2, leftover_fangraphs, by = c("Name", "birthDate"))
leftover_Master2_t$fangraphsID <- leftover_Master2_t$fangraphsID.y.y
dictionary <- rbind(dictionary, leftover_Master2_t[!is.na(leftover_Master2_t$fangraphsID), c("playerID", "bbrefID", "fangraphsID")])
fwrite(dictionary, "dictionary.csv")

leftover_fangraphs <- leftover_fangraphs[!(leftover_fangraphs$fangraphsID %in% leftover_Master2_t$fangraphsID),]
leftover_Master2 <- leftover_Master2[!(leftover_Master2$playerID %in% dictionary$playerID),]

leftover_Master2$Name <- gsub("[[:punct:]]", "", leftover_Master2$Name)
leftover_Master2_t <- leftover_Master2_t[order(leftover_Master2_t$Name), ]
leftover_Master2_t[1,"fangraphsID.y"] <- 1006417
leftover_Master2_t[2,"fangraphsID.y"] <- 1420
leftover_Master2_t[3,"fangraphsID.y"] <- 531

leftover_Master2_t <- left_join(leftover_Master2, leftover_fangraphs, by = c("birthDate"))

temp_adds <- leftover_Master2_t[!is.na(leftover_Master2_t$fangraphsID.y),]
fwrite(temp_adds, "temp_odds.csv")
temp_adds <- temp_adds[-c(1,3,16:260,262:947,949:1414,1418:1883, 1886, 1888:2120, 2124:2144, 2146:2356,2360:2826,2829:3294, 3296:3331, 3333:3528,3533:3766,3768:3805,3807:4000,4003:4043,4045:4235,4237:4278,4280:4469,4471,4475,4478,4484,4521:4753,4757:4811,4813:4989,4991:5223, 5231:5463,5472:5704,5707:5781,5783:5941,5944:6409,6411:6725,6727:7110,7114:7346,7355:7587,7592:7682,7684:8057,8059,8061:8293,8297:8995, 8997:9462,9465:9697,9704:9804,9806:9936,9938,9940:10405,10407:10639,10641,10643:11108,11123,11140:11838,11841:12192,12194:12306,12310:12542, 12546:12668,12670:12778,12784:12913,12915:13016,13021:14095,14097:14419,14424:14657,14660:14815,14817:14892,14895:15127,15136, 15139:15371,15374:15606,15608:15840,15848:16015,16017:16081,16083,16086:16784,16787,16791:16964,16966:17023,17029:17261,17275:17507, 17513:17745,17748:18213,18216:18448,18450:18639,18641:18682,18685:19383,19388:19620,19623:19855,19858,19862:20094,20096:20761, 20763:20794,20797:20999,21001:21702,21704:21961,21963,21966:22176,22178:22198,22201,22204:22436,22438,22440:22672,22691:22907, 22909:22923,22926,22936:23154,23156:23168,23174:23395,23397:23406,23408,23411,23413,23417:23882,23884:24116,24119:24351),]
temp_adds$fangraphsID <- temp_adds$fangraphsID.y
dictionary <- rbind(dictionary, temp_adds[,c("playerID", "bbrefID", "fangraphsID")])
fwrite(dictionary, "dictionary.csv")


leftover_Master2 <- leftover_Master2[!(leftover_Master2$playerID %in% dictionary$playerID),]
leftover_fangraphs <- leftover_fangraphs[!(leftover_fangraphs$fangraphsID %in% dictionary$fangraphsID),]



Master2 <- left_join(Master2, fan_pitch, by = "fangraphsID")
Master2 <- left_join(Master2, fan_bat, by = "fangraphsID")
Master2$fWAR <- ifelse(is.na(Master2$fWAR_bat) & is.na(Master2$fWAR_pitch), NA, ifelse(is.na(Master2$fWAR_bat), 0, Master2$fWAR_bat) + ifelse(is.na(Master2$fWAR_pitch), 0, Master2$fWAR_pitch))



# Baseball Reference WAR

data("Master")
rWAR <- data.frame(playerID = Master$playerID, bbrefID = Master$bbrefID, finalGame = Master$finalGame, rWAR = NA, rWAR_batting = NA, rWAR_pitching = NA)
rWAR[7443,"bbrefID"] <- "harribe01"
rWAR <- rWAR[-c(5905, 9450),]
rWAR <- rWAR[str_sub(rWAR$bbrefID, -2, -1) != "99",]

get_rWAR <- function(row) {
  if (!is.na(row["bbrefID"]) & !is.na(row["finalGame"])) {
    page <- read_html(paste0("https://www.baseball-reference.com/players/", substr(row["bbrefID"], 1, 1), "/", row["bbrefID"], ".shtml"))
    total <- page %>% html_nodes(".p1 div:nth-child(1) p+ p") %>% html_text() %>% as.numeric()
    if (length(total) == 0) total <- page %>% html_nodes(".p1 div:nth-child(1) p") %>% html_text() %>% as.numeric()
    new_page <- page %>% html_nodes(xpath = '//comment()') %>% html_text() %>% paste(collapse = '') %>% read_html()
    batting <- new_page %>% html_nodes("#batting_value tfoot tr:nth-child(1) .right:nth-child(14)") %>% html_text() %>% as.numeric()
    if (length(batting) == 0) batting <- NA
    pitching <- new_page %>% html_nodes("#pitching_value tfoot tr:nth-child(1) .right:nth-child(17)") %>% html_text() %>% as.numeric()
    if (length(pitching) == 0) pitching <- NA
    return(c(total, batting, pitching))
  }
  return(NA)
}

get_rWAR2 <- function(row) {
  page <- read_html(paste0("https://www.baseball-reference.com/players/", substr(row["bbrefID"], 1, 1), "/", row["bbrefID"], ".shtml"))
  total <- page %>% html_nodes(".p1 div:nth-child(1) p+ p") %>% html_text() %>% as.numeric()
  if (length(total) == 0) total <- page %>% html_nodes(".p1 div:nth-child(1) p") %>% html_text() %>% as.numeric()
  new_page <- page %>% html_nodes(xpath = '//comment()') %>% html_text() %>% paste(collapse = '') %>% read_html()
  
  batting <- new_page %>% html_nodes("#batting_value tfoot tr:nth-child(1) .right:nth-child(14)") %>% html_text() %>% as.numeric()
  if (length(batting) == 0) batting <- 0
  
  pitching <- new_page %>% html_nodes("#pitching_value .poptip:nth-child(13)") %>% html_text()
  if (length(pitching) == 0) {
    pitching <- 0
  } else if (pitching == "RA9extras") {
    pitching <- new_page %>% html_nodes("#pitching_value tfoot tr:nth-child(1) .right:nth-child(18)") %>% html_text() %>% as.numeric()
  } else {
    pitching <- new_page %>% html_nodes("#pitching_value tfoot tr:nth-child(1) .right:nth-child(17)") %>% html_text() %>% as.numeric()
  }

  return(c(total, batting, pitching))
}

t <- 0
for (i in 7860:dim(rWAR)[1]) {
  t <- t + 1/dim(rWAR)[1]
  print(t)
  rWAR[i,c("rWAR", "rWAR_batting", "rWAR_pitching")] <- get_rWAR2(rWAR[i,])
}
rWAR[is.na(rWAR$rWAR_pitching),"rWAR_pitching"] <- 0

rWAR <- rWAR %>% select(playerID, bbrefID, rWAR, rWAR_batting, rWAR_pitching)
fwrite(rWAR, "rWAR.csv")
```



Compute other statistics

```{r}
# Batting

batting_career$AVG <- batting_career$H.B / batting_career$AB
batting_career$X1B <- batting_career$H.B - batting_career$X2B - batting_career$X3B - batting_career$HR.B
batting_career$SLG <- (batting_career$X1B + 2*batting_career$X2B + 3*batting_career$X3B + 4*batting_career$HR.B) / batting_career$AB
batting_career$PA <- batting_career$AB + batting_career$BB.B + replace_na(batting_career$HBP.B, 0) + replace_na(batting_career$SF.B, 0) + replace_na(batting_career$SH.B, 0) 
batting_career$OBP <- (batting_career$H.B + batting_career$BB.B + replace_na(batting_career$HBP.B, 0)) / (batting_career$PA - replace_na(batting_career$SH.B, 0))
batting_career$OPS <- batting_career$OBP + batting_career$SLG
batting_career$SBP <- batting_career$SB / (batting_career$SB + batting_career$CS)

final_batting <- batting_career %>% dplyr::select(playerID, firstyearID.B, lastyearID.B, BB.B, G.B, AB, H.B, HR.B, AVG, R, RBI, SB, OBP, SLG, OPS)

# Pitching

pitching_career$AB.P <- pitching_career$BFP - pitching_career$BB.P - replace_na(pitching_career$HBP.P, 0) - replace_na(pitching_career$SF.P, 0) - replace_na(pitching_career$SH.P, 0)
pitching_career$BAOpp <- pitching_career$H.P / pitching_career$AB.P
pitching_career$WHIP <- (pitching_career$BB.P + pitching_career$H.P) / (pitching_career$IPout / 3)
pitching_career$IP <- pitching_career$IPout / 3

final_pitching <- pitching_career %>% dplyr::select(playerID, firstyearID.P, lastyearID.P, W, L, ERA, G.P, GS, SV, IP, SO.P, WHIP)
```

```{r Hall of Fame Dataset}
data("HallOfFame")
HallOfFame2 <- data.frame()
HallOfFame <- HallOfFame %>% filter(category == "Player" & ((votedBy == "Veterans" & inducted == 'Y') | votedBy != "Veterans") & votedBy != "Nominating Vote") %>% mutate(percentVote = votes / ballots)
for (i in sort(unique(HallOfFame$playerID))) {
  temp <- HallOfFame %>% filter(playerID == i) 
  bbwaa <- temp %>% filter(votedBy == "BBWAA" | votedBy == "Special Election" | votedBy == "Final Ballot")
  induction <- temp %>% filter(inducted == 'Y')
  lastYear <- temp %>% filter(yearID == max(yearID))
  perVote <- na.omit(temp$percentVote)
  HallOfFame2 <- rbind(HallOfFame2, data.frame(playerID = i, firstYearHOF = min(temp$yearID), lastYearHOF = max(temp$yearID), ballots = dim(bbwaa)[1], inducted = as.logical(dim(induction)[1]), votedBy = ifelse(dim(induction)[1] > 0, induction$votedBy, NA), percentVote = ifelse(length(perVote) == 0, NA, max(perVote))))
}
HallOfFame2$onBallot <- HallOfFame2$ballots > 0
HallOfFame2[HallOfFame2$playerID == "clemero01", "percentVote"] <- 393/420
HallOfFame2[HallOfFame2$playerID == "gehrilo01", "percentVote"] <- NA
fwrite(HallOfFame2, "hof.csv")
```

```{r Fielding Data}
data("Fielding")
Fielding[is.na(Fielding$E), "E"] <- 0

Fielding2 <- data.frame()
for (i in unique(Fielding$playerID)) {
  temp <- Fielding %>% filter(playerID == i)
  Fielding2 <- rbind(Fielding2, data.frame(playerID = i, PO = sum(temp$PO), A = sum(temp$A), E = sum(temp$E)))
}


Fielding2 <- Fielding2 %>% select(playerID, PO, A, E)
fwrite(Fielding2, "positions.csv")
```

```{r Position/Team}
data("Appearances")
data("Teams")

Appearances <- left_join(Appearances, Teams, by = c("teamID", "yearID")) 
Appearances$wPer <- Appearances$W / Appearances$G 
apps <- data.frame()
for(i in unique(Appearances$playerID)) {
  temp <- Appearances %>% filter(playerID == i)
  most_games <- 0
  for (j in unique(temp$teamID)) {
    curr_games <- sum(temp[temp$teamID == j,"G_all"])
    if(curr_games > most_games) {
      most_team <- j
      most_games <- curr_games
    }
  }
  apps <- rbind(apps, data.frame(playerID = i, career_len = length(unique(temp$yearID)), team = most_team, wPer = sum((temp$G_all*temp$wPer)/sum(temp$G_all)), P = sum(temp$G_p), C = sum(temp$G_c), X1B = sum(temp$G_1b), X2B = sum(temp$G_2b), X3B = sum(temp$G_3b), SS = sum(temp$G_ss), LF = sum(temp$G_lf), CF = sum(temp$G_cf), RF = sum(temp$G_rf), DH = sum(temp$G_dh), PH = sum(temp$G_ph), PR = sum(temp$G_pr)))
}


apps[is.na(apps$DH),"DH"] <- 0
apps[is.na(apps$PH),"PH"] <- 0
apps[is.na(apps$PR),"PR"] <- 0
pos <- c("P", "C", "1B", "2B", "3B", "SS", "LF", "CF", "RF", "DH", "PH", "PR")
pos_d <- c("P", "C", "1B", "2B", "3B", "SS", "LF", "CF", "RF")
apps$position <- pos[apply(apps[,c(5:16)], 1, order)[12,]]
apps$pos_d <- pos_d[apply(apps[,c(5:13)], 1, order)[9,]]

apps$pitchPer <- apps$P / (apps$P + apps$C + apps$X1B + apps$X2B + apps$X3B + apps$SS + apps$RF + apps$CF + apps$LF + apps$DH + apps$PH + apps$PR)
apps$batPer <- (apps$C + apps$X1B + apps$X2B + apps$X3B + apps$SS + apps$RF + apps$CF + apps$LF + apps$DH + apps$PH) / (apps$P + apps$C + apps$X1B + apps$X2B + apps$X3B + apps$SS + apps$RF + apps$CF + apps$LF + apps$DH + apps$PH + apps$PR)

apps <- apps %>% select(playerID, career_len, team, position, pos_d, wPer, pitchPer, batPer)
fwrite(apps, "apps.csv")
```

```{r Player Awards}
data("AwardsPlayers")

awards2 <- data.frame()
for (i in unique(AwardsPlayers$playerID)) {
  temp <- AwardsPlayers %>% filter(playerID == i)
  awards2 <- rbind(awards2, data.frame(playerID = i, goldGloves = sum(temp$awardID == "Gold Glove"), MVPs = sum(temp$awardID == "Most Valuable Player"), CYaward = sum(temp$awardID == "Cy Young Award"), BRaward = sum(temp$awardID == "Branch Rickey Award"), CBPoY = sum(temp$awardID == "Comeback Player of the Year"), HAaward = sum(temp$awardID == "Hank Aaron Award"), hutch = sum(temp$awardID == "Hutch Award"), LGMaward = sum(temp$awardID == "Lou Gehrig Memorial Award"), PTC = sum(temp$awardID == "Pitching Triple Crown"), ReloY = sum(temp$awardID == "Reliever of the Year Award"), RCaward = sum(temp$awardID == "Roberto Clemente Award"), RRMaward = sum(temp$awardID == "Rolaids Relief Man Award"), RoY = sum(temp$awardID == "Rookie of the Year"), SS = sum(temp$awardID == "Silver Slugger"), TC = sum(temp$awardID == "Triple Crown")))
}

fwrite(awards2, "awards.csv")
```


```{r Post season data}
data("AllstarFull")

allstars <- data.frame()
for (i in unique(AllstarFull$playerID)) {
  temp <- AllstarFull %>% filter(playerID == i) 
  allstars <- rbind(allstars, data.frame(playerID = i, aStarApp = length(unique(temp$yearID))))
}
fwrite(allstars, "allstars.csv")
```

```{r Postseason Batting}
data("BattingPost")
data("SeriesPost")

batPost <- data.frame()
for (i in unique(BattingPost$playerID)) {
  temp <- BattingPost %>% filter(playerID == i)
  batPost <- rbind(batPost, data.frame(playerID = i, GPost = sum(temp$G), H = sum(temp$H), AB = sum(temp$AB)))
}
batPost$BAPost <- batPost$H / batPost$AB


SeriesPost2 <- SeriesPost %>% filter(round == "WS" | round == "CS") %>% select(yearID, teamIDwinner, wins, losses)
colnames(SeriesPost2) <- c("yearID", "teamID", "WSWins", "WSLosses")
BattingPost2 <- BattingPost %>% filter(round == "WS" | round == "CS")
BattingPost2 <- left_join(BattingPost2, SeriesPost2, by = c("yearID", "teamID"))
SeriesPost2 <- SeriesPost %>% filter(round == "WS" | round == "CS") %>% select(yearID, teamIDloser, wins, losses)
colnames(SeriesPost2) <- c("yearID", "teamID", "WSLosses", "WSWins")
BattingPost2 <- left_join(BattingPost2, SeriesPost2, by = c("yearID", "teamID"))
BattingPost2$WSWins <- ifelse(is.na(BattingPost2$WSWins.x), 0, BattingPost2$WSWins.x) + ifelse(is.na(BattingPost2$WSWins.y), 0, BattingPost2$WSWins.y)
BattingPost2$WSLosses <- ifelse(is.na(BattingPost2$WSLosses.x), 0, BattingPost2$WSLosses.x) + ifelse(is.na(BattingPost2$WSLosses.y), 0, BattingPost2$WSLosses.y)

batPost2 <- data.frame()
for (i in unique(BattingPost2$playerID)) {
  temp <- BattingPost2 %>% filter(playerID == i)
  batPost2 <- rbind(batPost2, data.frame(playerID = i, WSW = sum(temp$WSWins), WSL = sum(temp$WSLosses)))
}

batPost <- left_join(batPost, batPost2, by = "playerID", all = TRUE)

batPost <- batPost %>% select(playerID, GPost, BAPost, WSW, WSL)
fwrite(batPost, "batPost.csv")
```

```{r Combine Stats to one dataframe}
rWAR <- fread("rWAR.csv")
data("Master")
hof <- fread("hof.csv")
positions <- fread("positions.csv")
awards <- fread("awards.csv")
allstars <- fread("allstars.csv")
apps <- fread("apps.csv")
batPost <- fread("batPost.csv")

Master2 <- left_join(Master, rWAR, by = "playerID")
Master2 <- left_join(Master2, hof, by = "playerID", all = TRUE)
Master2 <- left_join(Master2, positions, by = "playerID", all = TRUE)
Master2 <- left_join(Master2, awards, by = "playerID", all = TRUE)
Master2 <- left_join(Master2, allstars, by = "playerID",  all = TRUE)
Master2 <- left_join(Master2, apps, by = "playerID", all = TRUE)
Master2 <- left_join(Master2, batPost, by = "playerID", all = TRUE)
Master2[is.na(Master2$CYaward), "CYaward"] <- 0
Master2[is.na(Master2$BRaward), "BRaward"] <- 0
Master2[is.na(Master2$CBPoY), "CBPoY"] <- 0
Master2[is.na(Master2$HAaward), "HAaward"] <- 0
Master2[is.na(Master2$hutch), "hutch"] <- 0
Master2[is.na(Master2$LGMaward), "LGMaward"] <- 0
Master2[is.na(Master2$PTC), "PTC"] <- 0
Master2[is.na(Master2$ReloY), "ReloY"] <- 0
Master2[is.na(Master2$RCaward), "RCaward"] <- 0
Master2[is.na(Master2$RRMaward), "RRMaward"] <- 0
Master2[is.na(Master2$RoY), "RoY"] <- 0
Master2[is.na(Master2$SS), "SS"] <- 0
Master2[is.na(Master2$TC), "TC"] <- 0
Master2[is.na(Master2$GPost), "GPost"] <- 0
Master2[is.na(Master2$BAPost), "BAPost"] <- 0
Master2[is.na(Master2$WSW), "WSW"] <- 0
Master2[is.na(Master2$WSL), "WSL"] <- 0
Master2[is.na(Master2$aStarApp),"aStarApp"] <- 0
Master2[is.na(Master2$goldGloves),"goldGloves"] <- 0
Master2[is.na(Master2$MVPs),"MVPs"] <- 0
Master2[is.na(Master2$ballots), "ballots"] <- 0
Master2[is.na(Master2$inducted), "inducted"] <- FALSE
Master2[is.na(Master2$onBallot), "onBallot"] <- FALSE
Master2$banned <- FALSE
Master2[Master2$votedBy == "" & !is.na(Master2$votedBy), "votedBy"] <- NA

banned_players <- c("bechtge01", "devliji01", "hallge01", "nichoal01", "cravebi01", "highadi01", "o'conja01", "howelha01", "fogelho99", "chaseha01", "zimmehe01", "cicoted01", "willile01", "gandich01", "mcmulfr01", "risbesw01", "felscha01", "jacksjo01", "weavebu01", "gedeojo01", "paulege01", "kauffbe01", "mageele01", "douglph01", "o'conji01", "dolanco02", "rosepe01")

mitchell_report <- c("caminke01", "cansejo01", "dykstle01", "joynewa01", "mcgwima01", "turnbde01", "alexama02", "bonesri01", "cabreal02", "crawfpa02", "gonzaju03", "grimsja01", "palmera01", "benarma01", "bondsba01", "estalbo02", "giambja01", "giambje01", "riosar01", "santibe01", "sheffga01", "velarra01", "allench01", "bellmi02", "bennega01", "bigbila01", "brownke01", "carrema01", "chrisja01", "clarkho02", "clemero02", "custja01", "donnebr01", "donnech01", "francma01", "frankry01", "gagneer01", "hairsje02", "hergema01", "hiattph01", "hillgl01", "hundlto01", "juddmi01", "justida01", "knoblch01", "lakerti01", "lansimi01", "loducpa01", "loganno01", "manzajo01", "mckayco01", "merckke01", "miadiba01", "morriha02", "naultda01", "neaglde01", "parquji01", "pettian01", "piattad01", "prattto02", "randost01", "riggsad01", "roberbr01", "seguida01", "santaf.01", "stantmi02", "stoneri01", "tejadmi01", "vaughmo01", "villoro01", "vinafe01", "whitero02", "willije02", "willito02", "youngke01", "zaungr01", "ankieri01", "bellda01", "byrdpa01", "gibboja01", "glaustr01", "guilljo01", "holmeda01", "matthga02", "rockejo01", "schoesc01", "valdeis01", "willima04", "woodast01", 
                     "alfonel01", "almanca01", "almonab01", "asheral01", "bastaan01", "beckhti01", "betanra01", "braunry02", "byrdma01", "cabreev01", "cabreme01", "camermi01", "canoro01", "castiwe01", "cervefr01", "colabch01", "colonba01", "cruzne02", "frankry01", "galvifr01", "gibboja01", "gordode01", "grandya01", "grimsja01", "guilljo01", "heredfe01", "lawtoma02", "martest01", "martefr01", "maybica01", "mckiran01", "mejiaje01", "mondera02", "montafr02", "monteag01", "morsemi01", "motagu01", "palmera01", "pattotr01", "paulida01", "peraljh01", "perezne01", "pinedmi01", "polanjo01", "ramirma02", "rincoju01", "rodrial01", "rollida01", "romerj", "ruizca01", "salasju01", "sanchal03", "santaer01", "serafda01", "stanlco01", "stronja01", "stumpda01", "tejadmi01", "volqued01", "wrighst01", "catetr01", "collawi01", "cordofr01", "guzmaje01", "henslcl01", "macharo01", "mossda01", "mallebr01", "nunnajo01", "evansto01", "matosju01", "rodriri03", "robergr01", "torreei01", "ruizra01", "mcdonda02", "rodrigu01", "herrejo03", "smythst01", "tocajo01", "parkech01", "uguetlu01", "delgawi01", "castrra01", "labanjo01", "whitema02", "ruizra01", "ramirra02", "rodrine01", "nunezab01", "haadya01", "mccutda01", "crucefr01", "urdanli01", "saloman01", "jorgery01", "hackmlu01", "schafjo02", "cotahu01", "sosajo02", "hernaru03", "owenshe02", "mitrese01", "ozunapa01", "redmapr01", "lopezpe01", "quintom01", "kinnema01", "frandke01", "valdejo02", "monteje01", "escalse01", "martife02", "delosfa01", "norbejo01", "colomal01", "vizcaar01", "guerrja01", "delabst01", "jurrjja01", "alcanvi01", "puellce01", "choiji01", "gamboed01", "colonjo01", "chavimi01", "webblo01", "gonzalu01", "riosda01", "adducji02")

vets_comm <- c("haineje01", "bancrda01", "hafeych01", "youngro01", "kellyge01", "bottoji01", "lindsfr01")

Master2[Master2$playerID %in% vets_comm,"vets_comm"] <- TRUE
Master2[Master2$bbrefID.x %in% banned_players,"banned"] <- TRUE
Master2[Master2$bbrefID.x %in% mitchell_report, "steriods"] <- TRUE
Master2[is.na(Master2$steriods),"steriods"] <- FALSE
Master2[is.na(Master2$vets_comm),"vets_comm"] <- FALSE
Master2 <- Master2 %>% mutate(name = paste0(nameFirst, " ", nameLast))
Master2 <- left_join(Master2, final_batting, by = "playerID")
Master2 <- left_join(Master2, final_pitching, by = "playerID")
Master2 <- Master2 %>% dplyr::select(playerID, bbrefID.x, name, bats, throws, debut, finalGame, career_len, team, wPer, position, pos_d, PO, A, E, rWAR, pitchPer, batPer, firstyearID.B, lastyearID.B, rWAR_batting, AB, H.B, HR.B, BB.B, G.B, AVG, R, RBI, SB, OBP, SLG, OPS, firstyearID.P, lastyearID.P, rWAR_pitching, W, L, ERA, G.P, GS, SV, IP, SO.P, WHIP, GPost, BAPost, WSW, WSL, goldGloves, MVPs, CYaward, BRaward, CBPoY, HAaward, hutch, LGMaward, PTC, ReloY, RCaward, RRMaward, RoY, SS, TC, aStarApp, firstYearHOF, lastYearHOF, ballots, onBallot, inducted, votedBy, percentVote, banned, steriods, vets_comm)
colnames(Master2) <- c("playerID", "bbrefID", "name", "bats", "throws", "debut", "finalGame", "career_len", "team", "winPer", "position", "def_pos", "PO", "A", "E", "rWAR", "pitchPer", "batPer", "firstYearID.B", "lastYearID.B", "rWAR.B", "AB", "H", "HR", "BB", "G.B", "BA", "R", "RBI", "SB", "OBP", "SLG", "OPS", "firstYearID.P", "lastYearID.P", "rWAR.P", "W", "L", "ERA", "G.P", "GS", "SV", "IP", "SO", "WHIP", "GPost", "BAPost", "WSW", "WSL", "goldGloves", "MVPs", "CYaward", "BRaward", "CBPoY", "HAaward", "hutch", "LGMaward", "PTC", "ReloY", "RCaward", "RRMaward", "RoY", "SS", "TC", "allStarApps", "firstYearHOF", "lastYearHOF", "ballots", "onBallot", "inducted", "votedBy", "percentVote", "banned", "steriods", "vets_comm")
Master2[Master2$AB == 0 & !is.na(Master2$AB),c("BA", "OBP", "SLG", "OPS")] <- NA

fwrite(Master2, "baseball.csv")
```




